ARG aws_account_id
ARG aws_region
ARG ecr_repo_name

FROM ${aws_account_id}.dkr.ecr.${aws_region}.amazonaws.com/${ecr_repo_name}:base
COPY ["wp-cli.phar", "serverless-wordpress-wp2static.zip","serverless-wordpress-s3-addon.zip","/tmp/"]
COPY docker-entrypoint.sh /usr/local/bin/
RUN apt-get update && apt-get install -y sudo jq awscli mariadb-client python3-boto3 python3-pip git binutils wget build-essential libwrap0-dev libssl-dev less
RUN pip3 install boto3
RUN pip3 install --target /usr/lib/python3/dist-packages botocore

# EFS utils
WORKDIR /src
RUN git clone https://github.com/aws/efs-utils
WORKDIR /src/efs-utils
RUN ./build-deb.sh
WORKDIR /src/efs-utils/build
RUN apt-get -y install ./amazon-efs-utils-1.33.3-1_all.deb

# Stunnel
WORKDIR /src/
RUN wget https://www.stunnel.org/downloads/stunnel-5.65.tar.gz
RUN tar xvfz stunnel-5.65.tar.gz
WORKDIR /src/stunnel-5.65
RUN ./configure
RUN make
RUN make install

# Wordpress user
WORKDIR /var/www/html
RUN usermod -s /bin/bash www-data

# true shit below
RUN chmod +x /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /tmp/wp-cli.phar
RUN mv /tmp/wp-cli.phar /usr/local/bin/wp
RUN rm -rf /var/lib/apt/lists/*

RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
COPY ["php.ini", "$PHP_INI_DIR/conf.d/"]
